name: dianwo

services:
  web:
    container_name: xuco-web
    image: ghcr.io/xuerzong/xuco.me:release
    ports:
      - 80:80
    restart: unless-stopped
    networks:
      - xuco

  umami:
    image: docker.umami.is/umami-software/umami:postgresql-latest
    ports:
      - 3000:3000
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - xuco
    environment:
      DATABASE_URL: postgres://${UMAMI_PG_USER}:${UMAMI_PG_PASSWORD}@postgres:5432/umami
      
  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${UMAMI_PG_USER}
      POSTGRES_PASSWORD: ${UMAMI_PG_PASSWORD}
      POSTGRES_DB: umami
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - xuco 
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${POSTGRES_USER}", "-d", "${POSTGRES_DB}"]
      interval: 30s
      timeout: 5s
      retries: 5

networks:
  xuco:
    driver: bridge

volumes:
  postgres-data:
    driver: local